spring.application.name=matricula

server.port=8090

server.servlet.context-path=/matricula/api

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPI}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=${CORREO}
spring.mail.password=${PASW_APLI}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

swagger.username=${SW_USER}
swagger.password=${SW_PASSWORD}